export interface PaymentData {
  id?: string;
  leaseId: string;
  amount: number;
  paymentDate?: string | null;
  dueDate?: string | null;
  paymentMethod: string;
  status: "paid" | "pending" | "late" | "cancelled" | "undefined" | "advanced";
  effectiveStatus?:
    | "paid"
    | "pending"
    | "late"
    | "undefined"
    | "advanced"
    | "cancelled";
  transactionId?: string | null;
  notes?: string | null;
  paymentType:
    | "initial"
    | "rent"
    | "deposit"
    | "deposit_return"
    | "agency_fee"
    | "other";
  isAutoGenerated: boolean;
  processedBy?: string | null;
  createdAt?: string;
}

export interface PaymentFrequency {
  value:
    | "daily"
    | "weekly"
    | "biweekly"
    | "monthly"
    | "quarterly"
    | "biannually"
    | "annually";
  label: string;
  daysInterval: number;
  periodUnit: "days" | "weeks" | "months" | "years";
  periodAmount: number;
}

export const PAYMENT_FREQUENCIES: PaymentFrequency[] = [
  {
    value: "daily",
    label: "Quotidien",
    daysInterval: 1,
    periodUnit: "days",
    periodAmount: 1,
  },
  {
    value: "weekly",
    label: "Hebdomadaire",
    daysInterval: 7,
    periodUnit: "weeks",
    periodAmount: 1,
  },
  {
    value: "biweekly",
    label: "Bi-hebdomadaire",
    daysInterval: 14,
    periodUnit: "weeks",
    periodAmount: 2,
  },
  {
    value: "monthly",
    label: "Mensuel",
    daysInterval: 30,
    periodUnit: "months",
    periodAmount: 1,
  },
  {
    value: "quarterly",
    label: "Trimestriel",
    daysInterval: 90,
    periodUnit: "months",
    periodAmount: 3,
  },
  {
    value: "biannually",
    label: "Semestriel",
    daysInterval: 180,
    periodUnit: "months",
    periodAmount: 6,
  },
  {
    value: "annually",
    label: "Annuel",
    daysInterval: 365,
    periodUnit: "years",
    periodAmount: 1,
  },
];

export const getPaymentFrequency = (value: string): PaymentFrequency => {
  return (
    PAYMENT_FREQUENCIES.find((f) => f.value === value) || PAYMENT_FREQUENCIES[3]
  ); // default to monthly
};

export interface BulkUpdateParams {
  paymentIds: string[];
  status?: "paid" | "pending" | "late" | "cancelled" | "undefined" | "advanced";
  notes?: string;
  userId?: string;
}
